---
# Copyright (c) Nicolas Lamirault <nicolas.lamirault@gmail.com>
#
# SPDX-License-Identifier: Apache-2.0

# These settings are synced to GitHub by https://probot.github.io/apps/settings/

repository:
  name: opentelemetry-lab
  description: OpenTelemetry laboratory
  homepage: https://github.com/nlamirault/opentelemetry-lab
  topics: opentelemetry
  private: false
  has_issues: true
  has_projects: true
  has_wiki: true
  has_downloads: true
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
  delete_branch_on_merge: true
  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true

# Labels: define labels for Issues and Pull Requests
labels:

## KIND

- name: "kind/renovate"
  description: "Categorizes issue or PR as related to Renovate"
  color: "FF0040"

- name: "kind/bug"
  description: "Categorizes issue or PR as related to a bug"
  color: "FF0040"

- name: "kind/discussion"
  description: "Categorizes issue or PR as related to a discussion"
  color: "fbca04"

- name: "kind/documentation"
  description: "Categorizes issue or PR as related to documentation"
  color: "5319e7"

- name: "kind/feature"
  description: "Categorizes issue or PR as related to a new feature"
  color: "1d76db"

- name: "kind/question"
  description: "Categorizes issue or PR as related to a question"
  color: "cc317c"

- name: "kind/deprecation"
  description: "Categorizes issue or PR as related to a feature/enhancement marked for deprecation"
  color: "cc317c"

- name: "kind/cleanup"
  description: "Categorizes issue or PR as related to cleaning up code, process, or technical debt"
  color: "cc317c"

- name: "kind/support"
  description: "Categorizes issue or PR as a support question"
  color: "cc317c"

## PRIORITY

- name: "priority/critical"
  description: "Highest priority. This should be dealt with ASAP"
  color: "ee0701"

- name: "priority/high"
  description: "After critical issues are fixed, these should be dealt with before any further issues"
  color: "d93f0b"

- name: "priority/medium"
  description: "This issue or PR may be useful, and needs some attention"
  color: "fbca04"

- name: "priority/low"
  description: "This issue can probably be picked up by anyone looking to contribute to the project, as an entry fix"
  color: "0e8a16"

- name: "priority/backlog"
  description: "Possibly useful, but not yet enough support to actually get it done"
  color: "fbca04"

## STATUS

- name: "status/abandoned"
  description: "This issue or PR is no longer important"
  color: "000000"

- name: "status/available"
  description: "No one has claimed responsibility for resolving this issue"
  color: "c2e0c6"

- name: "status/blocked"
  description: "There is another issue or PR that needs to be resolved first"
  color: "ee0701"

- name: "status/in_progress"
  description: "This issue or PR is being worked on, and has someone assigned"
  color: "cccccc"

- name: "status/on_hold"
  description: "Similar to blocked, but is assigned to someone"
  color: "e99695"

- name: "status/proposal"
  description: "A new propoal"
  color: "d4c5f9"

- name: "status/review_needed"
  description: "The issue or PR needs to be reviewed"
  color: "fbca04"

## LIFECYCLE

- name: "lifecycle/waiting"
  description: "Indicates that an issue or PR is waiting a contributor."
  color: "75CA20"

- name: "lifecycle/active"
  description: "Indicates that an issue or PR is actively being worked on by a contributor."
  color: "75CA20"

- name: "lifecycle/frozen"
  description: "Indicates that an issue or PR should not be auto-closed due to staleness."
  color: "10D3EE"

- name: "lifecycle/stale"
  description: "Denotes an issue or PR has remained open with no activity and has become stale."
  color: "616F6C"

- name: "lifecycle/rotten"
  description: "Denotes an issue or PR that has aged beyond stale and will be auto-closed."
  color: "212F3D"

## SIZE

- name: "size/xs"
  description: "Size XS"
  color: "ededed"

- name: "size/s"
  description: "Size S"
  color: "ededed"

- name: "size/m"
  description: "Size M"
  color: "ededed"

- name: "size/l"
  description: "Size L"
  color: "ededed"

- name: "size/xl"
  description: "Size XL"
  color: "ededed"

## NEEDS

- name: "needs/triage"
  description: "Indicates an issue or PR lacks a `triage/foo` label and requires one."
  color: "D669BE"

- name: "needs/priority"
  description: "Indicates a PR lacks a `priority/foo` label and requires one."
  color: "D669BE"

- name: "needs/kind"
  description: "Indicates a PR lacks a `kind/foo` label and requires one."
  color: "D669BE"

- name: "needs/lifecycle"
  description: "Indicates a PR lacks a `lifecycle/foo` label and requires one."
  color: "D669BE"

- name: "needs/area"
  description: "Indicates an issue or PR lacks a `area/foo` label and requires one."
  color: "D669BE"

- name: "needs/size"
  description: "Indicates an issue or PR lacks a `size/foo` label and requires one."
  color: "D669BE"

- name: "needs/status"
  description: "Indicates an issue or PR lacks a `status/foo` label and requires one."
  color: "D669BE"

## AREA

- name: "area/github"
  description: "Github"
  color: "cc317c"

- name: "area/go"
  description: "Go"
  color: "cc317c"

- name: "area/python"
  description: "Python"
  color: "cc317c"

- name: "area/java"
  description: "Java"
  color: "cc317c"

- name: "area/javascript"
  description: "Javascript"
  color: "cc317c"

- name: "area/rust"
  description: "Rust"
  color: "cc317c"

- name: "area/swift"
  description: "Swift"
  color: "cc317c"

## DEPENDENCY

- name: "dependency/github"
  description: "Dependency Github Actions"
  color: "6fcb70"

milestones:
- title: v1.0.0
  description: v1.0.0
  state: open
- title: v2.0.0
  description: v2.0.0
  state: open

# Collaborators: give specific users access to this repository.
# See https://docs.github.com/en/rest/reference/repos#add-a-repository-collaborator for available options
collaborators:
# - username: bkeepers
#   permission: push
# - username: hubot
#   permission: pull

# Note: `permission` is only valid on organization-owned repositories.
# The permission to grant the collaborator. Can be one of:
# * `pull` - can pull, but not push to or administer this repository.
# * `push` - can pull and push, but not administer this repository.
# * `admin` - can pull, push and administer this repository.
# * `maintain` - Recommended for project managers who need to manage the repository without access to sensitive or destructive actions.
# * `triage` - Recommended for contributors who need to proactively manage issues and pull requests without write access.

# See https://docs.github.com/en/rest/reference/teams#add-or-update-team-repository-permissions for available options
teams:
- name: core
  # The permission to grant the team. Can be one of:
  # * `pull` - can pull, but not push to or administer this repository.
  # * `push` - can pull and push, but not administer this repository.
  # * `admin` - can pull, push and administer this repository.
  # * `maintain` - Recommended for project managers who need to manage the repository without access to sensitive or destructive actions.
  # * `triage` - Recommended for contributors who need to proactively manage issues and pull requests without write access.
  permission: admin
- name: collaborators
  permission: push
- name: docs
  permission: push

branches:
- name: main
  # https://docs.github.com/en/rest/reference/repos#update-branch-protection
  # Branch Protection settings. Set to null to disable
  protection:
    # Required. Require at least one approving review on a pull request, before merging. Set to null to disable.
    required_pull_request_reviews:
      # The number of approvals required. (1-6)
      required_approving_review_count: 1
      # Dismiss approved reviews automatically when a new commit is pushed.
      dismiss_stale_reviews: true
      # Blocks merge until code owners have reviewed.
      require_code_owner_reviews: true
      # Specify which users and teams can dismiss pull request reviews. Pass an empty dismissal_restrictions object to disable. User and team dismissal_restrictions are only available for organization-owned repositories. Omit this parameter for personal repositories.
      dismissal_restrictions:
        users: []
        teams: []
    # Required. Require status checks to pass before merging. Set to null to disable
    required_status_checks:
      # Required. Require branches to be up to date before merging.
      strict: true
      # Required. The list of status checks to require in order to merge into this branch
      contexts: []
    # Required. Enforce all configured restrictions for administrators. Set to true to enforce required status checks for repository administrators. Set to null to disable.
    enforce_admins: true
    # Prevent merge commits from being pushed to matching branches
    required_linear_history: true
    # Required. Restrict who can push to this branch. Team and user restrictions are only available for organization-owned repositories. Set to null to disable.
    restrictions:
      apps: []
      users: []
      teams: []
