---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
    args:
    - '--allow-multiple-documents'
    exclude: mkdocs.yml
  - id: check-added-large-files
- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.5.5
  hooks:
  - id: insert-license
    stages: [commit]
    files: (Makefile|\.mk|\.yaml|\.yml|\.toml|\.go|\.py|\.rs|\.java|\.js)
    args:
    - --license-filepath
    - hack/LICENSE.txt
    # - --remove-header
