# SPDX-FileCopyrightText: Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
# SPDX-License-Identifier: Apache-2.0

---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
    args:
    - '--allow-multiple-documents'
    exclude: mkdocs.yml
  - id: check-added-large-files
- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.5.5
  hooks:
  - id: insert-license
    stages: [commit]
    files: (Makefile|Dockerfile|\.mk|\.yaml|\.yml|\.toml|\.py)
    exclude: (\.json)
    args:
    - --license-filepath
    - hack/LICENSE.txt
    # - --remove-header
- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.5.5
  hooks:
  - id: insert-license
    stages: [commit]
    files: (\.go|\.rs|\.js|\.ts|\.java|\.swift|\.tsx|\.json5)
    exclude: (\.json)
    args:
    - --license-filepath
    - hack/LICENSE.txt
    - --comment-style
    - '//'
    # - --remove-header
- repo: https://github.com/spinergie/pre-commit-dprint
  rev: v0.45.0
  hooks:
  - id: dprint
    stages: [commit]
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.11.8
  hooks:
    # Run the linter
    - id: ruff
      args: [ --fix ]
    # Run the formatter
    - id: ruff-format
