---
x-common: &common
  networks:
  - opentelemetry-lab
  restart: unless-stopped
  logging:
    options:
      max-size: 50m
      max-file: "3"

services:

  otel-collector:
    <<: *common
    image: otel/opentelemetry-collector-contrib:0.147.0
    container_name: otel
    command:
    - "--config=/conf/config.yaml"
    volumes:
    - ./etc/otel/otel-collector-victoriastack.yaml:/conf/config.yaml
    ports:
    - "4317:4317" # OTLP gRPC receiver
    - "4318:4318" # OTLP http receiver
    - "8888:8888" # Prometheus metrics exporter
    - "8889:8889" # Prometheus metrics exporter
    environment:
    - OTEL_EXPORTER_OTLP_LOGS_ENDPOINT=http://victorialogs:9428/insert/opentelemetry/v1/logs
    - OTEL_EXPORTER_OTLP_METRICS_ENDPOINT=http://victoriametrics:8428/opentelemetry
    - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://victoriatraces:10428/insert/opentelemetry/v1/traces
    - OTEL_RESOURCE_ATTRIBUTES=deployment.environment.name=docker,service.name=otel-collector,service.criticality=low,service.version=0.147.0

  victoriametrics:
    <<: *common
    image: victoriametrics/victoria-metrics:v1.128.0
    ports:
    - "8428:8428"
    command:
    - "--storageDataPath=/storage"
    - "--opentelemetry.usePrometheusNaming=true"
    volumes:
    - "vmdata:/storage"
    environment:
    - OTEL_RESOURCE_ATTRIBUTES=deployment.environment.name=docker,service.name=victoriametrics,service.criticality=low,service.version=v1.128.0

  victorialogs:
    <<: *common
    image: victoriametrics/victoria-logs:v1.36.1
    ports:
    - "9428:9428"
    command:
    - "--storageDataPath=/vlogs"
    volumes:
    - "vldata:/vlogs"
    environment:
    - OTEL_RESOURCE_ATTRIBUTES=deployment.environment.name=docker,service.name=victorialogs,service.criticality=low,service.version=v1.36.1

  victoriatraces:
    <<: *common
    image: victoriametrics/victoria-traces:v0.4.0
    ports:
    - "10428:10428"
    command:
    - "--storageDataPath=/vtraces"
    - "--servicegraph.enableTask=true"
    volumes:
    - "vtdata:/vtraces"
    environment:
    - OTEL_RESOURCE_ATTRIBUTES=deployment.environment.name=docker,service.name=victoriatraces,service.criticality=low,service.version=v0.4.0

  grafana:
    <<: *common
    image: grafana/grafana:12.4.0
    ports:
    - "3000:3000"
    volumes:
    # - "grdata:/var/lib/grafana"
    - ./etc/grafana/dashboards-victoriastack.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
    - ./etc/grafana/datasource-victoriastack.yml:/etc/grafana/provisioning/datasources/datasource.yml
    - ./etc/grafana/dashboards/victoriastack:/var/lib/grafana/dashboards
    environment:
    - GF_AUTH_ANONYMOUS_ENABLED=true
    - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    - GF_AUTH_DISABLE_LOGIN_FORM=true
    - GF_INSTALL_PLUGINS=victoriametrics-metrics-datasource,victoriametrics-logs-datasource
    - OTEL_RESOURCE_ATTRIBUTES=deployment.environment.name=docker,service.name=grafana,service.criticality=low,service.version=12.4.0

volumes:
  vmdata: {}
  vldata: {}
  vtdata: {}
  # grdata: {}
