{
 "title": "OpenTelemetry / Collector / Health",
 "description": "A dashboard for monitoring the health of OpenTelemetry Collector instances using their internal metrics.",
 "tags": [
  "otelcol",
  "collector",
  "opentelemetry",
  "victoriametrics",
  "victoriastack"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "datasource",
    "label": "Data source",
    "query": "victoriametrics-metrics-datasource"
   },
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(otelcol_process_uptime_seconds_total,service_name)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(otelcol_process_uptime_seconds_total{service_name=~\"$service\"},service_instance_id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Running collectors",
   "type": "stat",
   "description": "Running collectors",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count({__name__=~\"otelcol_process_uptime(_seconds_total)?\", service_name=~\"$service\",service_instance_id=~\"$instance\"})\n"
    }
   ]
  },
  {
   "title": "Collector uptime",
   "type": "table",
   "description": "Collector uptime",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "{__name__=~\"otelcol_process_uptime(_seconds_total)?\", service_name=~\"$service\", service_instance_id=~\"$instance\"}\n",
     "legendFormat": "{{service_name}}/{{service_instance_id}}"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "description": "CPU usage",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (service_name, service_instance_id) (\n    rate(\n        {\n            __name__=~\"otelcol_process_cpu_seconds(_total)?\",\n            service_name=~\"$service\", service_instance_id=~\"$instance\"\n        }\n    [$__rate_interval])\n)\n",
     "legendFormat": "{{service_name}} / {{service_instance_id}}"
    }
   ]
  },
  {
   "title": "Memory (RSS)",
   "type": "timeseries",
   "description": "Memory (RSS)",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (service_name, service_instance_id) (\n  {__name__=~\"otelcol_process_memory_rss(_bytes)?\", service_name=~\"$service\", service_instance_id=~\"$instance\"}\n)\n",
     "legendFormat": "RSS - {{service_name}} / {{service_instance_id}}"
    }
   ]
  },
  {
   "title": "Memory (heap alloc)",
   "type": "timeseries",
   "description": "Memory (heap alloc)",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (service_name, service_instance_id) (\n  {__name__=~\"otelcol_process_runtime_total_sys_memory_bytes(_total)?\", service_name=~\"$service\", service_instance_id=~\"$instance\"}\n)\n",
     "legendFormat": "RSS - {{service_name}} / {{service_instance_id}}"
    }
   ]
  },
  { "title": "Receivers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Accepted metric points",
   "type": "timeseries",
   "description": "Accepted metric points",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(service_name, receiver) (rate({__name__=~\"otelcol_receiver_accepted_metric_points(_total)?\", service_name=~\"$service\", service_instance_id=~\"$instance\"}[$__rate_interval]))\n",
     "legendFormat": "{{service_name}} / {{receiver}}"
    }
   ]
  },
  {
   "title": "Accepted log records",
   "type": "timeseries",
   "description": "Accepted log records",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(service_name, receiver) (rate({__name__=~\"otelcol_receiver_accepted_log_records(_total)?\", service_name=~\"$service\", service_instance_id=~\"$instance\"}[$__rate_interval]))\n",
     "legendFormat": "{{service_name}} / {{receiver}}"
    }
   ]
  },
  {
   "title": "Accepted spans",
   "type": "timeseries",
   "description": "Accepted spans",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(service_name, receiver) (rate({__name__=~\"otelcol_receiver_accepted_spans(_total)?\", service_name=~\"$job\",service_instance_id=~\"$instance\"}[$__rate_interval]))\n",
     "legendFormat": "{{service_name}} / {{receiver}}"
    }
   ]
  },
  {
   "title": "Refused metric points",
   "type": "timeseries",
   "description": "Refused metric points",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(service_name, receiver) (rate({__name__=~\"otelcol_receiver_refused_metric_points(_total)?\", service_name=~\"$job\", service_instance_id=~\"$instance\"}[$__rate_interval]))\n",
     "legendFormat": "{{service_name}} / {{receiver}}"
    }
   ]
  },
  {
   "title": "Refused log records",
   "type": "timeseries",
   "description": "Refused log records",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(service_name, receiver) (rate({__name__=~\"otelcol_receiver_refused_log_records(_total)?\", service_name=~\"$service\", service_instance_id=~\"$instance\"}[$__rate_interval]))\n",
     "legendFormat": "{{service_name}} / {{receiver}}"
    }
   ]
  },
  {
   "title": "Refused spans",
   "type": "timeseries",
   "description": "Refused spans",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(job, receiver) (rate({__name__=~\"otelcol_receiver_refused_spans(_total)?\", service_name=~\"$service\",service_instance_id=~\"$instance\"}[$__rate_interval]))\n",
     "legendFormat": "{{service_name}}/{{receiver}}"
    }
   ]
  },
  {
   "title": "Processors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Metric Points",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(job, processor) (rate({__name__=~\"otelcol_processor_incoming_items(_total)?\", service_name=~\"$service\",service_instance_id=~\"$instance\", otel_signal=\"metrics\"}[$__rate_interval]))",
       "legendFormat": "{{service_name}} - {{processor}}"
      },
      {
       "expr": "sum by(job, processor) (rate({__name__=~\"otelcol_processor_outgoing_items(_total)?\", service_name=~\"$service\",service_instance_id=~\"$instance\", otel_signal=\"metrics\"}[$__rate_interval]))",
       "legendFormat": "{{service_name}} - {{processor}}"
      }
     ]
    },
    {
     "title": "Logs Records",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(job, processor) (rate({__name__=~\"otelcol_processor_incoming_items(_total)?\", service_name=~\"$service\",service_instance_id=~\"$instance\", otel_signal=\"logs\"}[$__rate_interval]))",
       "legendFormat": "{{service_name}} - {{processor}}"
      },
      {
       "expr": "sum by(job, processor) (rate({__name__=~\"otelcol_processor_outgoing_items(_total)?\", service_name=~\"$service\",service_instance_id=~\"$instance\", otel_signal=\"logs\"}[$__rate_interval]))",
       "legendFormat": "{{service_name}} - {{processor}}"
      }
     ]
    },
    {
     "title": "Spans",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(job, processor) (rate({__name__=~\"otelcol_processor_incoming_items(_total)?\", service_name=~\"$service\",service_instance_id=~\"$instance\", otel_signal=\"traces\"}[$__rate_interval]))",
       "legendFormat": "{{service_name}} - {{processor}}"
      },
      {
       "expr": "sum by(job, processor) (rate({__name__=~\"otelcol_processor_outgoing_items(_total)?\", service_name=~\"$service\",service_instance_id=~\"$instance\", otel_signal=\"traces\"}[$__rate_interval]))",
       "legendFormat": "{{service_name}} - {{processor}}"
      }
     ]
    },
    {
     "title": "Accepted metric points",
     "type": "timeseries",
     "description": "Accepted metric points",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(job, receiver) (rate({__name__=~\"otelcol_processor_accepted_metric_points(_total)?\", service_name=~\"$service\",service_instance_id=~\"$instance\"}[$__rate_interval]))\n",
       "legendFormat": "{{service_name}}/{{receiver}}"
      }
     ]
    },
    {
     "title": "Accepted log records",
     "type": "timeseries",
     "description": "Accepted log records",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(job, receiver) (rate({__name__=~\"otelcol_processor_accepted_log_records(_total)?\", service_name=~\"$service\",service_instance_id=~\"$instance\"}[$__rate_interval]))\n",
       "legendFormat": "{{service_name}}/{{receiver}}"
      }
     ]
    },
    {
     "title": "Accepted spans",
     "type": "timeseries",
     "description": "Accepted spans",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(job, processor) (rate({__name__=~\"otelcol_processor_accepted_spans(_total)?\", service_name=~\"$service\",service_instance_id=~\"$instance\"}[$__rate_interval]))\n",
       "legendFormat": "{{service_name}} - {{processor}}"
      }
     ]
    },
    {
     "title": "Batch size send trigger",
     "type": "timeseries",
     "description": "Batch size send trigger",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(job, processor) (rate({__name__=~\"otelcol_processor_batch_timeout_trigger_send(_total)?\", service_name=~\"$service\",service_instance_id=~\"$instance\"}[$__rate_interval]))\n",
       "legendFormat": "{{service_name}}/{{processor}}"
      }
     ]
    },
    {
     "title": "Batch timeout send trigger",
     "type": "timeseries",
     "description": "Batch timeout send trigger",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(job, processor) (rate({__name__=~\"otelcol_processor_batch_timeout_trigger_send(_total)?\", service_name=~\"$service\",service_instance_id=~\"$instance\"}[$__rate_interval]))\n",
       "legendFormat": "{{service_name}}/{{processor}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Exporters",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "Exported metrics",
     "type": "timeseries",
     "description": "Exported metrics",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(job, exporter) (rate({__name__=~\"otelcol_exporter_sent_metric_points(_total)?\", service_name=~\"$service\",service_instance_id=~\"$instance\"}[$__rate_interval]))\n",
       "legendFormat": "{{service_name}}/{{exporter}}"
      }
     ]
    },
    {
     "title": "Exported logs",
     "type": "timeseries",
     "description": "Exported logs",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(job, exporter) (rate({__name__=~\"otelcol_exporter_sent_log_records(_total)?\", service_name=~\"$service\",service_instance_id=~\"$instance\"}[$__rate_interval]))\n",
       "legendFormat": "{{service_name}}/{{exporter}}"
      }
     ]
    },
    {
     "title": "Exported spans",
     "type": "timeseries",
     "description": "Exported spans",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(job, exporter) (rate({__name__=~\"otelcol_exporter_sent_spans(_total)?\", service_name=~\"$service\",service_instance_id=~\"$instance\"}[$__rate_interval]))\n",
       "legendFormat": "{{service_name}}/{{exporter}}"
      }
     ]
    },
    {
     "title": "Failed metrics",
     "type": "timeseries",
     "description": "Failed metrics",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(job, exporter) (rate({__name__=~\"otelcol_exporter_send_failed_metric_points(_total)?\", service_name=~\"$service\",service_instance_id=~\"$instance\"}[$__rate_interval]))\n",
       "legendFormat": "{{service_name}}/{{exporter}}"
      }
     ]
    },
    {
     "title": "Failed logs",
     "type": "timeseries",
     "description": "Failed logs",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(job, exporter) (rate({__name__=~\"otelcol_exporter_send_failed_log_records(_total)?\", service_name=~\"$service\",service_instance_id=~\"$instance\"}[$__rate_interval]))\n",
       "legendFormat": "{{service_name}}/{{exporter}}"
      }
     ]
    },
    {
     "title": "Failed spans",
     "type": "timeseries",
     "description": "Failed spans",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(job, exporter) (rate({__name__=~\"otelcol_exporter_send_failed_spans(_total)?\", service_name=~\"$service\",service_instance_id=~\"$instance\"}[$__rate_interval]))\n",
       "legendFormat": "{{service_name}}/{{exporter}}"
      }
     ]
    },
    {
     "title": "Enqueue failed metrics",
     "type": "timeseries",
     "description": "Enqueue failed metrics",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(job, exporter) (rate({__name__=~\"otelcol_exporter_enqueue_failed_metric_points(_total)?\", service_name=~\"$service\",service_instance_id=~\"$instance\"}[$__rate_interval]))\n",
       "legendFormat": "{{service_name}}/{{exporter}}"
      }
     ]
    },
    {
     "title": "Enqueue failed logs",
     "type": "timeseries",
     "description": "Enqueue failed logs",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(job, exporter) (rate({__name__=~\"otelcol_exporter_enqueue_failed_log_records(_total)?\", service_name=~\"$service\",service_instance_id=~\"$instance\"}[$__rate_interval]))\n",
       "legendFormat": "{{service_name}}/{{exporter}}"
      }
     ]
    },
    {
     "title": "Enqueue failed spans",
     "type": "timeseries",
     "description": "Enqueue failed spans",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(job, exporter) (rate({__name__=~\"otelcol_exporter_enqueue_failed_spans(_total)?\", service_name=~\"$service\",service_instance_id=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "{{service_name}}/{{exporter}}"
      }
     ]
    },
    {
     "title": "Exporter Queue Capacity",
     "type": "timeseries",
     "description": "Fixed capacity of the retry queue (in batches)",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "min(otelcol_exporter_queue_capacity{job=\"$job\"}) by (exporter)",
       "legendFormat": "Queue capacity: {{exporter}} {{service_instance_id}}"
      }
     ]
    },
    {
     "title": "Exporter Queue Size",
     "type": "timeseries",
     "description": "Current size of the retry queue (in batches)",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max(otelcol_exporter_queue_size{job=\"$job\"}) by (exporter)",
       "legendFormat": "Max queue size: {{exporter}} {{service_instance_id}}"
      }
     ]
    },
    {
     "title": "Exporter Queue Usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "max(\r\n    otelcol_exporter_queue_size{\r\n        job=\"$job\"\r\n    }\r\n) by (exporter)\r\n/\r\nmin(\r\n    otelcol_exporter_queue_capacity{\r\n        job=\"$job\"\r\n    }\r\n) by (exporter)",
       "legendFormat": "Queue capacity usage: {{exporter}} {{service_instance_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network traffic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "Inbound gRPC request duration percentiles",
     "type": "timeseries",
     "description": "Inbound gRPC request duration percentiles",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum by (job, instance, le) (rate({__name__=~\"rpc_server_duration_milliseconds_bucket\", service_name=~\"$service\",service_instance_id=~\"$instance\"}[$__rate_interval])))\n",
       "legendFormat": "p50 - {{service_name}}/{{service_instance_id}}"
      },
      {
       "expr": "histogram_quantile(0.90, sum by (job, instance, le) (rate({__name__=~\"rpc_server_duration_milliseconds_bucket\", service_name=~\"$service\",service_instance_id=~\"$instance\"}[$__rate_interval])))\n",
       "legendFormat": "p90 - {{service_name}}/{{service_instance_id}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum by (job, instance, le) (rate({__name__=~\"rpc_server_duration_milliseconds_bucket\", service_name=~\"$service\",service_instance_id=~\"$instance\"}[$__rate_interval])))\n",
       "legendFormat": "p99 - {{service_name}}/{{service_instance_id}}"
      }
     ]
    },
    {
     "title": "Inbound HTTP request duration percentiles",
     "type": "timeseries",
     "description": "Inbound HTTP request duration percentiles",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum by (job, instance, le) (rate({__name__=~\"http_server_request_duration_seconds_bucket\", service_name=~\"$service\",service_instance_id=~\"$instance\"}[$__rate_interval])))\n",
       "legendFormat": "p50 - {{service_name}}/{{service_instance_id}}"
      },
      {
       "expr": "histogram_quantile(0.90, sum by (job, instance, le) (rate({__name__=~\"http_server_request_duration_seconds_bucket\", service_name=~\"$service\",service_instance_id=~\"$instance\"}[$__rate_interval])))\n",
       "legendFormat": "p90 - {{service_name}}/{{service_instance_id}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum by (job, instance, le) (rate({__name__=~\"http_server_request_duration_seconds_bucket\", service_name=~\"$service\",service_instance_id=~\"$instance\"}[$__rate_interval])))\n",
       "legendFormat": "p99 - {{service_name}}/{{service_instance_id}}"
      }
     ]
    },
    {
     "title": "Inbound gRPC request size percentiles",
     "type": "timeseries",
     "description": "Inbound gRPC request size percentiles",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum by (job, instance, le) (rate({__name__=~\"rpc_server_request_size_bytes_bucket\", service_name=~\"$service\",service_instance_id=~\"$instance\"}[$__rate_interval])))\n",
       "legendFormat": "p50 - {{service_name}}/{{service_instance_id}}"
      },
      {
       "expr": "histogram_quantile(0.90, sum by (job, instance, le) (rate({__name__=~\"rpc_server_request_size_bytes_bucket\", service_name=~\"$service\",service_instance_id=~\"$instance\"}[$__rate_interval])))\n",
       "legendFormat": "p90 - {{service_name}}/{{service_instance_id}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum by (job, instance, le) (rate({__name__=~\"rpc_server_request_size_bytes_bucket\", service_name=~\"$service\",service_instance_id=~\"$instance\"}[$__rate_interval])))\n",
       "legendFormat": "p99 - {{service_name}}/{{service_instance_id}}"
      }
     ]
    },
    {
     "title": "Inbound HTTP request size percentiles",
     "type": "timeseries",
     "description": "Inbound HTTP request size percentiles",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum by (job, instance, le) (rate({__name__=~\"http_server_request_body_size_bytes_bucket\", service_name=~\"$service\",service_instance_id=~\"$instance\"}[$__rate_interval])))\n",
       "legendFormat": "p50 - {{service_name}}/{{service_instance_id}}"
      },
      {
       "expr": "histogram_quantile(0.90, sum by (job, instance, le) (rate({__name__=~\"http_server_request_body_size_bytes_bucket\", service_name=~\"$service\",service_instance_id=~\"$instance\"}[$__rate_interval])))\n",
       "legendFormat": "p90 - {{service_name}}/{{service_instance_id}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum by (job, instance, le) (rate({__name__=~\"http_server_request_body_size_bytes_bucket\", service_name=~\"$service\",service_instance_id=~\"$instance\"}[$__rate_interval])))\n",
       "legendFormat": "p99 - {{service_name}}/{{service_instance_id}}"
      }
     ]
    },
    {
     "title": "Outgoing gRPC request duration percentiles",
     "type": "timeseries",
     "description": "Outgoing gRPC request duration percentiles",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum by (job, instance, le) (rate({__name__=~\"rpc_client_duration_milliseconds_bucket\", service_name=~\"$service\",service_instance_id=~\"$instance\"}[$__rate_interval])))\n",
       "legendFormat": "p50 - {{service_name}}/{{service_instance_id}}"
      },
      {
       "expr": "histogram_quantile(0.90, sum by (job, instance, le) (rate({__name__=~\"rpc_client_duration_milliseconds_bucket\", service_name=~\"$service\",service_instance_id=~\"$instance\"}[$__rate_interval])))\n",
       "legendFormat": "p90 - {{service_name}}/{{service_instance_id}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum by (job, instance, le) (rate({__name__=~\"rpc_client_duration_milliseconds_bucket\", service_name=~\"$service\",service_instance_id=~\"$instance\"}[$__rate_interval])))\n",
       "legendFormat": "p99 - {{service_name}}/{{service_instance_id}}"
      }
     ]
    },
    {
     "title": "Outgoing HTTP request duration percentiles",
     "type": "timeseries",
     "description": "Outgoing HTTP request duration percentiles",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum by (job, instance, le) (rate({__name__=~\"http_client_request_duration_seconds_bucket\", service_name=~\"$service\",service_instance_id=~\"$instance\"}[$__rate_interval])))\n",
       "legendFormat": "p50 - {{service_name}}/{{service_instance_id}}"
      },
      {
       "expr": "histogram_quantile(0.90, sum by (job, instance, le) (rate({__name__=~\"http_client_request_duration_seconds_bucket\", service_name=~\"$service\",service_instance_id=~\"$instance\"}[$__rate_interval])))\n",
       "legendFormat": "p90 - {{service_name}}/{{service_instance_id}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum by (job, instance, le) (rate({__name__=~\"http_client_request_duration_seconds_bucket\", service_name=~\"$service\",service_instance_id=~\"$instance\"}[$__rate_interval])))\n",
       "legendFormat": "p99 - {{service_name}}/{{service_instance_id}}"
      }
     ]
    },
    {
     "title": "Outgoing gRPC request size percentiles",
     "type": "timeseries",
     "description": "Outgoing gRPC request size percentiles",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum by (job, instance, le) (rate({__name__=~\"rpc_client_request_size(_bytes_?)_bucket\", service_name=~\"$service\",service_instance_id=~\"$instance\"}[$__rate_interval])))\n",
       "legendFormat": "p50 - {{service_name}}/{{service_instance_id}}"
      },
      {
       "expr": "histogram_quantile(0.90, sum by (job, instance, le) (rate({__name__=~\"rpc_client_request_size(_bytes_?)_bucket\", service_name=~\"$service\",service_instance_id=~\"$instance\"}[$__rate_interval])))\n",
       "legendFormat": "p90 - {{service_name}}/{{service_instance_id}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum by (job, instance, le) (rate({__name__=~\"rpc_client_request_size(_bytes_?)_bucket\", service_name=~\"$service\",service_instance_id=~\"$instance\"}[$__rate_interval])))\n",
       "legendFormat": "p99 - {{service_name}}/{{service_instance_id}}"
      }
     ]
    },
    {
     "title": "Outgoing HTTP request size percentiles",
     "type": "timeseries",
     "description": "Outgoing HTTP request size percentiles",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum by (job, instance, le) (rate({__name__=~\"http_client_request_body_size_bytes_bucket\", service_name=~\"$service\",service_instance_id=~\"$instance\"}[$__rate_interval])))\n",
       "legendFormat": "p50 - {{service_name}}/{{service_instance_id}}"
      },
      {
       "expr": "histogram_quantile(0.90, sum by (job, instance, le) (rate({__name__=~\"http_client_request_body_size_bytes_bucket\", service_name=~\"$service\",service_instance_id=~\"$instance\"}[$__rate_interval])))\n",
       "legendFormat": "p90 - {{service_name}}/{{service_instance_id}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum by (job, instance, le) (rate({__name__=~\"http_client_request_body_size_bytes_bucket\", service_name=~\"$service\",service_instance_id=~\"$instance\"}[$__rate_interval])))\n",
       "legendFormat": "p99 - {{service_name}}/{{service_instance_id}}"
      }
     ]
    }
   ]
  }
 ]
}