# SPDX-FileCopyrightText: Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
# SPDX-License-Identifier: Apache-2.0

---
# config file version
apiVersion: 1

datasources:
- uid: prometheus
  orgId: 1
  name: Prometheus
  type: prometheus
  typeName: Prometheus
  access: proxy
  url: http://prometheus:9090
  editable: true
  jsonData:
    timeInterval: 60s
    exemplarTraceIdDestinations:
    - name: traceID
      datasourceUid: tempo
      urlDisplayLabel: 'Trace: $${__value.raw}'
    httpMethod: POST
- uid: loki
  name: Loki
  type: loki
  url: http://loki:3100
  editable: true
  jsonData:
    derivedFields:
    - name: 'trace_id'
      matcherType: 'label'
      matcherRegex: 'trace_id'
      url: '$${__value.raw}'
      datasourceUid: 'tempo'
      urlDisplayLabel: 'Trace: $${__value.raw}'
- uid: tempo
  orgId: 1
  name: Tempo
  type: tempo
  typeName: Tempo
  access: proxy
  url: http://tempo:3200
  editable: true
  jsonData:
    tracesToLogsV2:
      customQuery: true
      datasourceUid: 'loki'
      query: '{$${__tags}} | trace_id = "$${__trace.traceId}"'
      tags:
      - key: 'service.name'
        value: 'service_name'
    serviceMap:
      datasourceUid: 'prometheus'
    search:
      hide: false
    nodeGraph:
      enabled: true
    lokiSearch:
      datasourceUid: 'loki'
- name: Pyroscope
  orgId: 1
  type: grafana-pyroscope-datasource
  uid: pyroscope
  access: proxy
  url: http://pyroscope:4040
  editable: true
