# Copyright (c) Nicolas Lamirault <nicolas.lamirault@gmail.com>
#
# SPDX-License-Identifier: Apache-2.0

---
# config file version
apiVersion: 1

datasources:
- uid: prometheus
  orgId: 1
  name: Prometheus
  type: prometheus
  typeName: Prometheus
  access: proxy
  url: http://qryn:3100
  password: ''
  user: ''
  database: ''
  basicAuth: false
  isDefault: true
  jsonData:
    timeInterval: 60s
    exemplarTraceIdDestinations:
    - name: traceID
      datasourceUid: tempo
      urlDisplayLabel: 'Trace: $${__value.raw}'
    httpMethod: POST
  readOnly: false
  editable: true
- uid: loki
  orgId: 1
  name: Loki
  type: loki
  access: proxy
  url: http://qryn:3100
  jsonData:
    derivedFields:
    - name: 'trace_id'
      matcherType: 'label'
      matcherRegex: '^.*?traceI[d|D]=(\w+).*$'
      url: '$${__value.raw}'
      datasourceUid: 'tempo'
      urlDisplayLabel: 'Trace: $${__value.raw}'
  editable: true
- uid: tempo
  orgId: 1
  name: Tempo
  type: tempo
  typeName: Tempo
  access: proxy
  url: http://qryn:3100
  password: ''
  user: ''
  database: ''
  basicAuth: false
  isDefault: false
  jsonData:
    tracesToLogsV2:
      customQuery: true
      datasourceUid: loki
      query: '{$${__tags}} | trace_id = "$${__trace.traceId}"'
      tags:
      - key: 'service.name'
        value: 'service_name'
    tracesToMetrics:
      datasourceUid: prometheus
      tags: ['job']
    serviceMap:
      datasourceUid: prometheus
    search:
      hide: false
    nodeGraph:
      enabled: true
    lokiSearch:
      datasourceUid: loki
  readOnly: false
  editable: true
- uid: clickhouse
  orgId: 1
  name: ClickHouse
  type: grafana-clickhouse-datasource
  jsonData:
    defaultDatabase: qryn
    port: 9000
    host: clickhouse
    username: qryn
    tlsSkipVerify: false
    secureJsonData:
      password: qryn
