{
 "title": "OpenTelemetry / Collector / Health",
 "description": "A dashboard for monitoring the health of OpenTelemetry Collector instances using their internal metrics.",
 "tags": [
  "otelcol",
  "collector",
  "opentelemetry",
  "prometheus",
  "lgtm"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(otelcol_process_uptime_seconds_total,job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(otelcol_process_uptime_seconds_total{job=~\"$job\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Running collectors",
     "type": "stat",
     "description": "Running collectors",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count({__name__=~\"otelcol_process_uptime(_seconds_total)?\", job=~\"$job\",instance=~\"$instance\"})\n"
      }
     ]
    },
    {
     "title": "Collector uptime",
     "type": "table",
     "description": "Collector uptime",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "{__name__=~\"otelcol_process_uptime(_seconds_total)?\", job=~\"$job\",instance=~\"$instance\"}\n",
       "legendFormat": "{{job}}/{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU usage",
     "type": "timeseries",
     "description": "CPU usage",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (job, instance) (\n    rate(\n        {\n            __name__=~\"otelcol_process_cpu_seconds(_total)?\",\n            job=~\"$job\",instance=~\"$instance\"\n        }\n    [$__rate_interval])\n)\n",
       "legendFormat": "{{job}}/{{instance}}"
      }
     ]
    },
    {
     "title": "Memory (RSS)",
     "type": "timeseries",
     "description": "Memory (RSS)",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (job, instance) (\n  {__name__=~\"otelcol_process_memory_rss(_bytes)?\", job=~\"$job\",instance=~\"$instance\"}\n)\n",
       "legendFormat": "RSS - {{job}}/{{instance}}"
      }
     ]
    },
    {
     "title": "Memory (heap alloc)",
     "type": "timeseries",
     "description": "Memory (heap alloc)",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (job, instance) (\n  {__name__=~\"otelcol_process_runtime_total_sys_memory_bytes(_total)?\", job=~\"$job\",instance=~\"$instance\"}\n)\n",
       "legendFormat": "RSS - {{job}}/{{instance}}"
      }
     ]
    }
   ]
  },
  { "title": "Receivers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Accepted metric points",
   "type": "timeseries",
   "description": "Accepted metric points",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(job, receiver) (rate({__name__=~\"otelcol_receiver_accepted_metric_points(_total)?\", job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))\n",
     "legendFormat": "{{job}}/{{receiver}}"
    }
   ]
  },
  {
   "title": "Accepted log records",
   "type": "timeseries",
   "description": "Accepted log records",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(job, receiver) (rate({__name__=~\"otelcol_receiver_accepted_log_records(_total)?\", job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))\n",
     "legendFormat": "{{job}}/{{receiver}}"
    }
   ]
  },
  {
   "title": "Accepted spans",
   "type": "timeseries",
   "description": "Accepted spans",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(job, receiver) (rate({__name__=~\"otelcol_receiver_accepted_spans(_total)?\", job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))\n",
     "legendFormat": "{{job}}/{{receiver}}"
    }
   ]
  },
  {
   "title": "Refused metric points",
   "type": "timeseries",
   "description": "Refused metric points",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(job, receiver) (rate({__name__=~\"otelcol_receiver_refused_metric_points(_total)?\", job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))\n",
     "legendFormat": "{{job}}/{{receiver}}"
    }
   ]
  },
  {
   "title": "Refused log records",
   "type": "timeseries",
   "description": "Refused log records",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(job, receiver) (rate({__name__=~\"otelcol_receiver_refused_log_records(_total)?\", job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))\n",
     "legendFormat": "{{job}}/{{receiver}}"
    }
   ]
  },
  {
   "title": "Refused spans",
   "type": "timeseries",
   "description": "Refused spans",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(job, receiver) (rate({__name__=~\"otelcol_receiver_refused_spans(_total)?\", job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))\n",
     "legendFormat": "{{job}}/{{receiver}}"
    }
   ]
  },
  { "title": "Processors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Metric Points",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(job, processor) (rate({__name__=~\"otelcol_processor_incoming_items(_total)?\", job=~\"$job\",instance=~\"$instance\", otel_signal=\"metrics\"}[$__rate_interval]))",
     "legendFormat": "{{job}} - {{processor}}"
    },
    {
     "expr": "sum by(job, processor) (rate({__name__=~\"otelcol_processor_outgoing_items(_total)?\", job=~\"$job\",instance=~\"$instance\", otel_signal=\"metrics\"}[$__rate_interval]))",
     "legendFormat": "{{job}} - {{processor}}"
    }
   ]
  },
  {
   "title": "Logs Records",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(job, processor) (rate({__name__=~\"otelcol_processor_incoming_items(_total)?\", job=~\"$job\",instance=~\"$instance\", otel_signal=\"logs\"}[$__rate_interval]))",
     "legendFormat": "{{job}} - {{processor}}"
    },
    {
     "expr": "sum by(job, processor) (rate({__name__=~\"otelcol_processor_outgoing_items(_total)?\", job=~\"$job\",instance=~\"$instance\", otel_signal=\"logs\"}[$__rate_interval]))",
     "legendFormat": "{{job}} - {{processor}}"
    }
   ]
  },
  {
   "title": "Spans",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(job, processor) (rate({__name__=~\"otelcol_processor_incoming_items(_total)?\", job=~\"$job\",instance=~\"$instance\", otel_signal=\"traces\"}[$__rate_interval]))",
     "legendFormat": "{{job}} - {{processor}}"
    },
    {
     "expr": "sum by(job, processor) (rate({__name__=~\"otelcol_processor_outgoing_items(_total)?\", job=~\"$job\",instance=~\"$instance\", otel_signal=\"traces\"}[$__rate_interval]))",
     "legendFormat": "{{job}} - {{processor}}"
    }
   ]
  },
  {
   "title": "Accepted metric points",
   "type": "timeseries",
   "description": "Accepted metric points",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(job, receiver) (rate({__name__=~\"otelcol_processor_accepted_metric_points(_total)?\", job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))\n",
     "legendFormat": "{{job}}/{{receiver}}"
    }
   ]
  },
  {
   "title": "Accepted log records",
   "type": "timeseries",
   "description": "Accepted log records",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(job, receiver) (rate({__name__=~\"otelcol_processor_accepted_log_records(_total)?\", job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))\n",
     "legendFormat": "{{job}}/{{receiver}}"
    }
   ]
  },
  {
   "title": "Accepted spans",
   "type": "timeseries",
   "description": "Accepted spans",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(job, processor) (rate({__name__=~\"otelcol_processor_accepted_spans(_total)?\", job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))\n",
     "legendFormat": "{{job}} - {{processor}}"
    }
   ]
  },
  {
   "title": "Batch size send trigger",
   "type": "timeseries",
   "description": "Batch size send trigger",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(job, processor) (rate({__name__=~\"otelcol_processor_batch_timeout_trigger_send(_total)?\", job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))\n",
     "legendFormat": "{{job}}/{{processor}}"
    }
   ]
  },
  {
   "title": "Batch timeout send trigger",
   "type": "timeseries",
   "description": "Batch timeout send trigger",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(job, processor) (rate({__name__=~\"otelcol_processor_batch_timeout_trigger_send(_total)?\", job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))\n",
     "legendFormat": "{{job}}/{{processor}}"
    }
   ]
  },
  { "title": "Exporters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Exported metrics",
   "type": "timeseries",
   "description": "Exported metrics",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(job, exporter) (rate({__name__=~\"otelcol_exporter_sent_metric_points(_total)?\", job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))\n",
     "legendFormat": "{{job}}/{{exporter}}"
    }
   ]
  },
  {
   "title": "Exported logs",
   "type": "timeseries",
   "description": "Exported logs",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(job, exporter) (rate({__name__=~\"otelcol_exporter_sent_log_records(_total)?\", job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))\n",
     "legendFormat": "{{job}}/{{exporter}}"
    }
   ]
  },
  {
   "title": "Exported spans",
   "type": "timeseries",
   "description": "Exported spans",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(job, exporter) (rate({__name__=~\"otelcol_exporter_sent_spans(_total)?\", job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))\n",
     "legendFormat": "{{job}}/{{exporter}}"
    }
   ]
  },
  {
   "title": "Failed metrics",
   "type": "timeseries",
   "description": "Failed metrics",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(job, exporter) (rate({__name__=~\"otelcol_exporter_send_failed_metric_points(_total)?\", job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))\n",
     "legendFormat": "{{job}}/{{exporter}}"
    }
   ]
  },
  {
   "title": "Failed logs",
   "type": "timeseries",
   "description": "Failed logs",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(job, exporter) (rate({__name__=~\"otelcol_exporter_send_failed_log_records(_total)?\", job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))\n",
     "legendFormat": "{{job}}/{{exporter}}"
    }
   ]
  },
  {
   "title": "Failed spans",
   "type": "timeseries",
   "description": "Failed spans",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(job, exporter) (rate({__name__=~\"otelcol_exporter_send_failed_spans(_total)?\", job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))\n",
     "legendFormat": "{{job}}/{{exporter}}"
    }
   ]
  },
  {
   "title": "Enqueue failed metrics",
   "type": "timeseries",
   "description": "Enqueue failed metrics",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(job, exporter) (rate({__name__=~\"otelcol_exporter_enqueue_failed_metric_points(_total)?\", job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))\n",
     "legendFormat": "{{job}}/{{exporter}}"
    }
   ]
  },
  {
   "title": "Enqueue failed logs",
   "type": "timeseries",
   "description": "Enqueue failed logs",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(job, exporter) (rate({__name__=~\"otelcol_exporter_enqueue_failed_log_records(_total)?\", job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))\n",
     "legendFormat": "{{job}}/{{exporter}}"
    }
   ]
  },
  {
   "title": "Enqueue failed spans",
   "type": "timeseries",
   "description": "Enqueue failed spans",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(job, exporter) (rate({__name__=~\"otelcol_exporter_enqueue_failed_spans(_total)?\", job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{job}}/{{exporter}}"
    }
   ]
  },
  {
   "title": "Exporter Queue Capacity",
   "type": "timeseries",
   "description": "Fixed capacity of the retry queue (in batches)",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "min(otelcol_exporter_queue_capacity{job=\"$job\"}) by (exporter)",
     "legendFormat": "Queue capacity: {{exporter}} {{service_instance_id}}"
    }
   ]
  },
  {
   "title": "Exporter Queue Size",
   "type": "timeseries",
   "description": "Current size of the retry queue (in batches)",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(otelcol_exporter_queue_size{job=\"$job\"}) by (exporter)",
     "legendFormat": "Max queue size: {{exporter}} {{service_instance_id}}"
    }
   ]
  },
  {
   "title": "Exporter Queue Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max(\r\n    otelcol_exporter_queue_size{\r\n        job=\"$job\"\r\n    }\r\n) by (exporter)\r\n/\r\nmin(\r\n    otelcol_exporter_queue_capacity{\r\n        job=\"$job\"\r\n    }\r\n) by (exporter)",
     "legendFormat": "Queue capacity usage: {{exporter}} {{service_instance_id}}"
    }
   ]
  },
  {
   "title": "Network traffic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 },
   "collapsed": true,
   "panels": [
    {
     "title": "Inbound gRPC request duration percentiles",
     "type": "timeseries",
     "description": "Inbound gRPC request duration percentiles",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 176 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum by (job, instance, le) (rate({__name__=~\"rpc_server_duration_milliseconds_bucket\", job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])))\n",
       "legendFormat": "p50 - {{job}}/{{instance}}"
      },
      {
       "expr": "histogram_quantile(0.90, sum by (job, instance, le) (rate({__name__=~\"rpc_server_duration_milliseconds_bucket\", job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])))\n",
       "legendFormat": "p90 - {{job}}/{{instance}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum by (job, instance, le) (rate({__name__=~\"rpc_server_duration_milliseconds_bucket\", job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])))\n",
       "legendFormat": "p99 - {{job}}/{{instance}}"
      }
     ]
    },
    {
     "title": "Inbound HTTP request duration percentiles",
     "type": "timeseries",
     "description": "Inbound HTTP request duration percentiles",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 176 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum by (job, instance, le) (rate({__name__=~\"http_server_request_duration_seconds_bucket\", job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])))\n",
       "legendFormat": "p50 - {{job}}/{{instance}}"
      },
      {
       "expr": "histogram_quantile(0.90, sum by (job, instance, le) (rate({__name__=~\"http_server_request_duration_seconds_bucket\", job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])))\n",
       "legendFormat": "p90 - {{job}}/{{instance}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum by (job, instance, le) (rate({__name__=~\"http_server_request_duration_seconds_bucket\", job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])))\n",
       "legendFormat": "p99 - {{job}}/{{instance}}"
      }
     ]
    },
    {
     "title": "Inbound gRPC request size percentiles",
     "type": "timeseries",
     "description": "Inbound gRPC request size percentiles",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 184 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum by (job, instance, le) (rate({__name__=~\"rpc_server_request_size_bytes_bucket\", job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])))\n",
       "legendFormat": "p50 - {{job}}/{{instance}}"
      },
      {
       "expr": "histogram_quantile(0.90, sum by (job, instance, le) (rate({__name__=~\"rpc_server_request_size_bytes_bucket\", job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])))\n",
       "legendFormat": "p90 - {{job}}/{{instance}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum by (job, instance, le) (rate({__name__=~\"rpc_server_request_size_bytes_bucket\", job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])))\n",
       "legendFormat": "p99 - {{job}}/{{instance}}"
      }
     ]
    },
    {
     "title": "Inbound HTTP request size percentiles",
     "type": "timeseries",
     "description": "Inbound HTTP request size percentiles",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 184 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum by (job, instance, le) (rate({__name__=~\"http_server_request_body_size_bytes_bucket\", job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])))\n",
       "legendFormat": "p50 - {{job}}/{{instance}}"
      },
      {
       "expr": "histogram_quantile(0.90, sum by (job, instance, le) (rate({__name__=~\"http_server_request_body_size_bytes_bucket\", job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])))\n",
       "legendFormat": "p90 - {{job}}/{{instance}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum by (job, instance, le) (rate({__name__=~\"http_server_request_body_size_bytes_bucket\", job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])))\n",
       "legendFormat": "p99 - {{job}}/{{instance}}"
      }
     ]
    },
    {
     "title": "Outgoing gRPC request duration percentiles",
     "type": "timeseries",
     "description": "Outgoing gRPC request duration percentiles",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 192 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum by (job, instance, le) (rate({__name__=~\"rpc_client_duration_milliseconds_bucket\", job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])))\n",
       "legendFormat": "p50 - {{job}}/{{instance}}"
      },
      {
       "expr": "histogram_quantile(0.90, sum by (job, instance, le) (rate({__name__=~\"rpc_client_duration_milliseconds_bucket\", job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])))\n",
       "legendFormat": "p90 - {{job}}/{{instance}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum by (job, instance, le) (rate({__name__=~\"rpc_client_duration_milliseconds_bucket\", job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])))\n",
       "legendFormat": "p99 - {{job}}/{{instance}}"
      }
     ]
    },
    {
     "title": "Outgoing HTTP request duration percentiles",
     "type": "timeseries",
     "description": "Outgoing HTTP request duration percentiles",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 192 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum by (job, instance, le) (rate({__name__=~\"http_client_request_duration_seconds_bucket\", job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])))\n",
       "legendFormat": "p50 - {{job}}/{{instance}}"
      },
      {
       "expr": "histogram_quantile(0.90, sum by (job, instance, le) (rate({__name__=~\"http_client_request_duration_seconds_bucket\", job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])))\n",
       "legendFormat": "p90 - {{job}}/{{instance}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum by (job, instance, le) (rate({__name__=~\"http_client_request_duration_seconds_bucket\", job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])))\n",
       "legendFormat": "p99 - {{job}}/{{instance}}"
      }
     ]
    },
    {
     "title": "Outgoing gRPC request size percentiles",
     "type": "timeseries",
     "description": "Outgoing gRPC request size percentiles",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 200 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum by (job, instance, le) (rate({__name__=~\"rpc_client_request_size(_bytes_?)_bucket\", job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])))\n",
       "legendFormat": "p50 - {{job}}/{{instance}}"
      },
      {
       "expr": "histogram_quantile(0.90, sum by (job, instance, le) (rate({__name__=~\"rpc_client_request_size(_bytes_?)_bucket\", job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])))\n",
       "legendFormat": "p90 - {{job}}/{{instance}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum by (job, instance, le) (rate({__name__=~\"rpc_client_request_size(_bytes_?)_bucket\", job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])))\n",
       "legendFormat": "p99 - {{job}}/{{instance}}"
      }
     ]
    },
    {
     "title": "Outgoing HTTP request size percentiles",
     "type": "timeseries",
     "description": "Outgoing HTTP request size percentiles",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 200 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum by (job, instance, le) (rate({__name__=~\"http_client_request_body_size_bytes_bucket\", job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])))\n",
       "legendFormat": "p50 - {{job}}/{{instance}}"
      },
      {
       "expr": "histogram_quantile(0.90, sum by (job, instance, le) (rate({__name__=~\"http_client_request_body_size_bytes_bucket\", job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])))\n",
       "legendFormat": "p90 - {{job}}/{{instance}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum by (job, instance, le) (rate({__name__=~\"http_client_request_body_size_bytes_bucket\", job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])))\n",
       "legendFormat": "p99 - {{job}}/{{instance}}"
      }
     ]
    }
   ]
  }
 ]
}