# SPDX-FileCopyrightText: Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
# SPDX-License-Identifier: Apache-2.0

---
name: Project / Size PR

on: # yamllint disable-line rule:truthy
  pull_request:
    types: [opened, synchronize]

jobs:
  update_labels:
    runs-on: ubuntu-latest
    steps:
    - name: Monitor Actions
      uses: GitHubSecurityLab/actions-permissions/monitor@v1
      with:
        config: ${{ vars.PERMISSIONS_CONFIG }}

    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

    - uses: actions-ecosystem/action-size@v2
      id: size

    - uses: actions-ecosystem/action-remove-labels@v1
      with:
        github_token: ${{ secrets.github_token }}
        labels: ${{ steps.size.outputs.stale_labels }}

    - uses: actions-ecosystem/action-add-labels@v1
      with:
        github_token: ${{ secrets.github_token }}
        labels: ${{ steps.size.outputs.new_label }}
